spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ESUN;encrypt=false;
    username: sa
    password: sa
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect # SQL Server dialect
    hibernate:
      ddl-auto: none # Disable automatic schema management
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true # Show SQL queries
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true