spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ESUN;encrypt=false;
    username: sa
    password: sa
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true