CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY NOT NULL,  
    FLOOR_NO INT,
    SEAT_NO INT
);

CREATE TABLE Employee (
    EMP_ID BIGINT PRIMARY KEY,
    NAME NVARCHAR(100),
    EMAIL NVARCHAR(100),
    FLOOR_SEAT_SEQ INT,

    CONSTRAINT FK_Employee_SeatingChart 
        FOREIGN KEY (FLOOR_SEAT_SEQ) 
        REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);